version: '3.8'
name: pm-webapp
services:
  pmdb:
    container_name: pm-webapp-db
    image: postgres:14.1-alpine
    restart: always
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    ports:
      - '${POSTGRES_PORT}:5432'
    expose:
      - '${POSTGRES_PORT}'
    volumes: 
      - db:/var/lib/postgresql/data
volumes:
  db:
    driver: local