version: '3.8'
name: pm-webapp
services:
  pmdb:
    container_name: pm-webapp-db
    image: postgres:14.1-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=local_pm
    ports:
      - '8001:5432'
    expose:
      - '8001'
    volumes: 
      - db:/var/lib/postgresql/data
volumes:
  db:
    driver: local